/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

/**
 *
 * @author alarc
 */
public class ProcedureView extends javax.swing.JFrame {

    /**
     * Creates new form ProcedureView
     */
    public ProcedureView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNameP = new javax.swing.JLabel();
        txtNameP = new javax.swing.JTextField();
        labelPrice = new javax.swing.JLabel();
        txtPriceP = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        labelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNameP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelNameP.setForeground(new java.awt.Color(255, 255, 255));
        labelNameP.setText("Nome: ");
        getContentPane().add(labelNameP, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, 30));
        getContentPane().add(txtNameP, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 220, 30));

        labelPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelPrice.setForeground(new java.awt.Color(255, 255, 255));
        labelPrice.setText("Valor: ");
        getContentPane().add(labelPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, -1, 30));
        getContentPane().add(txtPriceP, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 180, 30));

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSave.setText("Salvar");
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 80, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Botox", "1000"},
                {"2", "Preenchimento Labial", "800"},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Procedimento", "Valor"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 560, 290));

        labelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/TelasMenu.png"))); // NOI18N
        getContentPane().add(labelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProcedureView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProcedureView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProcedureView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProcedureView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProcedureView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelBackground;
    private javax.swing.JLabel labelNameP;
    private javax.swing.JLabel labelPrice;
    private javax.swing.JTextField txtNameP;
    private javax.swing.JTextField txtPriceP;
    // End of variables declaration//GEN-END:variables
}
