/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

/**
 *
 * @author alarc
 */
public class ProcedurePerformedView extends javax.swing.JFrame {

    /**
     * Creates new form ProcedurePerformedView
     */
    public ProcedurePerformedView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelProcedureP = new javax.swing.JLabel();
        comboBoxProcedure = new javax.swing.JComboBox<>();
        labelDate = new javax.swing.JLabel();
        txtDateP = new javax.swing.JTextField();
        labelAmountReceived = new javax.swing.JLabel();
        txtAmountReceivedP = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        labelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelProcedureP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelProcedureP.setForeground(new java.awt.Color(255, 255, 255));
        labelProcedureP.setText("Procedimento: ");
        getContentPane().add(labelProcedureP, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, 30));

        comboBoxProcedure.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboBoxProcedure, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 210, 30));

        labelDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelDate.setForeground(new java.awt.Color(255, 255, 255));
        labelDate.setText("Data:");
        getContentPane().add(labelDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 40, 30));
        getContentPane().add(txtDateP, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 150, 30));

        labelAmountReceived.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelAmountReceived.setForeground(new java.awt.Color(255, 255, 255));
        labelAmountReceived.setText("Valor Recebido: ");
        getContentPane().add(labelAmountReceived, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 100, 30));
        getContentPane().add(txtAmountReceivedP, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 210, 30));

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSave.setText("Salvar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 80, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Botox", "04/03/2023", "1000"},
                {"2", "Preenchimento Labial", "04/03/2023", "800"},
                {null, null, null, null},
                {null, null, null, ""}
            },
            new String [] {
                "Id", "Procedimento", "Data", "Valor Recebido"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 560, 290));

        labelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Images/TelasMenu.png"))); // NOI18N
        getContentPane().add(labelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProcedurePerformedView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProcedurePerformedView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProcedurePerformedView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProcedurePerformedView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProcedurePerformedView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> comboBoxProcedure;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelAmountReceived;
    private javax.swing.JLabel labelBackground;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelProcedureP;
    private javax.swing.JTextField txtAmountReceivedP;
    private javax.swing.JTextField txtDateP;
    // End of variables declaration//GEN-END:variables
}
